{{- if .Values.persistence }}

apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: {{ include "monitoring.fullname" . }}


spec:

  accessModes:

  - ReadWriteOnce


  resources:

    requests:

      storage: {{ .Values.storage_size }}


  {{- if .Values.storageClassName }}

  storageClassName: {{ .Values.storageClassName }}

  {{- end }}

{{- end }}