apiVersion: v1
kind: Service

metadata:
  name: {{ include "monitoring.fullname" . }}

spec:

  type: {{ .Values.service.type }}

  selector:

    app: {{ include "monitoring.name" . }}

  ports:

  - port: {{ .Values.service.port }}

    targetPort: 80