apiVersion: v1
kind: Service
metadata:
  name: database-cluster
spec:
  clusterIP: None
  selector:
    app: database-cluster
  ports:
  - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-cluster
spec:
  serviceName: database-cluster
  replicas: 3
  selector:
    matchLabels:
      app: database-cluster
  template:
    metadata:
      labels:
        app: database-cluster
    spec:
      containers:
      - name: db
        image: postgres
        ports:
        - containerPort: 5432