apiVersion: v1
kind: Pod
metadata:
  name: db-critical
  namespace: default
spec:
  nodeName: worker-2
  containers:
  - name: db
    image: postgres
    volumeMounts:
    - name: data
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: data
    emptyDir: {}