apiVersion: v1
kind: Pod
metadata:
  name: database
  namespace: default
spec:
  nodeName: worker-2
  containers:
  - name: postgres
    image: postgres:16
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: nginx
        image: nginx